language: node_js

node_js: 0.12

env:
  global:
    - secure: ttYRBoOu1i75pvHmJ3csIkKej4TpqjlNYPsC9G6Z5DwqVdJRR3k+67YL7qNAcLt4F+ttDigzgzUkJ0tjsHCiB1YuuYS6s3HRcq1FkS4Pe0Z32GQUPIY07mwqTSAPceZtt9vFVbRHFkhHBWidUM+kEWeO1NcJ7EyHyx+AEkaQcsrk/kQAY20u5wBR9giGGFWQxtPOB9qZE3ok5fl6NiCTHiCl9PQWRMe7sLcC1y0p3QvRoWuv0877++BOvCKwarMb1LZE9YPaleCB5B22Gaao+RosfFstTpMQim3VW1EeW5WGtEAIqPK8byyrF9Z65thniOcJ9svghgkRVFWhaw9BL5/dzZmzY2I1gOtpFbe4omBVifKwSU8v0BYd7X5TmHbYrEE/cPXGBaVR+to1EbEPzq+MKKqVjlS+XYDpOH6HtEUdBm0sSbpK+1NUuvaCK96UY/jBfX1BQ6FWzt+pHzIaRKxVS9CZinmI95RX1kclyKFzP63lwbzHwqpxDJF5ZxRnP68rZjgScnACONJpH+tcVayK7Npy9x4ea08rI1gFl8HzMUWoTK2uttKaNfSIZdrIpyfFkD3MOKOTd9G6nY0aUCDWL4kpGO4zNpxQ7wVk7xYiy9aVCuR1+/1Eh8KFYOC6XnHuaXljaTPw8+wZIkBlsq6vprpLPhmMSC8U3WixXkM=
    - secure: rI9ZP86xxXDjuqDNg2AMzJm5haKgRTrYQx0ggA+mP4aF008T1ojxxBpUUE6vkUbCkcmJZsbIIVSvzpzZOUr7rP/Q39x4USyU5uEp1CFEhdwGDXProeIjvsyBWhIWUB3ojNbodZO8yRmkm+I3TpDEmbmXqr/5byY9YxnIOJd4MsNPdgD7/RePRbG+tdIVNBBPukt3Gg60eHyS8SSeIExbBT++F8O2dvTZL1fks6n8rV/36nOXP6fh7nrd6br1bhFG67fezXXF8m3sACUDZysur41hFNcdMwpMuVjs7ubHKypSuTxP1LxOwl7MhfKwbFtudTwIh2EM+AS89s8P0siRsbilb9YBcWRk20cL7DXFq+Spu+jIPn+7OE3CbQLeg8iEvO2vvCREouDbi1PweRCvI0MEM2+jVDs/T/0iivTFdituv2oUgPownSWTKRyAO5vtH3sAa+O7grPFc+hEiU+K9iOjkwt0P41W1ODWgw46hymvz9nLYjSqgBzHLI4LaOHj7bxSKWE/CL0Ek/f+HPPnvg9mG9zzma+Nb12+PD1SafzGrOohKR2pwbKCnDz+/vYPJNNI5QDKtDFcUE1XBv7Qc1KjPgZCFaPtYx8ry86WeOqi/ZgWJ3NSe6G/u80DOU1e6dW+S/spCtahINI5ZB13F7FS2/53IPrN2wtUm3XdUTY=

install:
  - npm install -g bower
  - npm install

script:
  - npm test

after_success:
  - npm run coveralls

notifications:
  email:
    on_failure: change
    on_success: change
